# uss golang to init proj
FROM golang:1.20.6

# meme
LABEL maintainer="Taota https://github.com/callme-taota"
LABEL description="SendUCode"

# workdir
WORKDIR /senducode-be

# cpoy go.mod and go.sum  and download
COPY go.mod go.sum ./
RUN go mod download

# copy
COPY . .

# build
RUN go build main.go

# expose
EXPOSE 3003

# do cmd
CMD ["./main"]